name:                toykell
version:             0.1.0
github:              "toykell/toykell"
license:             BSD3
author:              "Satoshi Ogata"
maintainer:          "satosystems@gmail.com"
copyright:           "(c) 2020 Satoshi Ogata"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Toy Haskell Compiler
category:            Compiler

description:         Please see the README on GitHub at <https://github.com/toykell/toykell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  toykell:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - toykell

tests:
  test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - toykell
